package com.tmuxes.terminal.emulator

import com.tmuxes.util.AppLogger
import com.tmuxes.util.AppLogger.Category

/**
 * Callback interface for events generated by the emulator that need to be
 * communicated back to the host (PTY / SSH channel / UI).
 */
interface TerminalListener {
    /** The terminal title changed (via OSC 0/1/2). */
    fun onTitleChanged(title: String) {}

    /** The terminal rang the bell (BEL, 0x07). */
    fun onBellRing() {}

    /** The terminal is sending a response back to the host (e.g. cursor position report). */
    fun onDataOutput(data: ByteArray) {}
}

/**
 * A VT100 / xterm-compatible terminal emulator.
 *
 * Feed raw bytes from the PTY into [processInput] and query the current screen
 * state through [buffer], cursor position, title, etc.
 *
 * Supported features:
 *   - Full UTF-8 decoding (1-4 byte sequences)
 *   - C0 control characters (BEL, BS, HT, LF, VT, FF, CR)
 *   - ESC sequences: save/restore cursor, index, reverse index, RIS
 *   - CSI sequences: cursor movement, erasing, scrolling, SGR (colors & attrs),
 *     DECSET/DECRST mode switches, device status reports
 *   - OSC sequences: window title
 *   - Scroll regions (DECSTBM)
 *   - Alternate screen buffer (mode 1049)
 *   - Bracketed paste mode (mode 2004)
 *   - Insert mode (mode 4)
 *   - Application cursor keys (mode 1)
 *   - Tab stops (HTS, TBC)
 */
class TerminalEmulator(
    private var rows: Int,
    private var columns: Int,
    private var maxScrollback: Int = TerminalBuffer.DEFAULT_SCROLLBACK
) {
    // -- Synchronization ------------------------------------------------

    private val lock = Any()

    // -- Public observable state ----------------------------------------

    @Volatile
    var buffer: TerminalBuffer = TerminalBuffer(rows, columns, maxScrollback)
        private set

    @Volatile
    var cursorRow: Int = 0
        private set
    @Volatile
    var cursorCol: Int = 0
        private set
    @Volatile
    var cursorVisible: Boolean = true
        private set

    var title: String = ""
        private set

    // -- Listener -------------------------------------------------------

    @Volatile var listener: TerminalListener? = null

    /** Callback for sending emulator responses (e.g., DA reply) back to SSH. */
    @Volatile var dataOutputCallback: ((ByteArray) -> Unit)? = null

    // -- Content change listeners ----------------------------------------

    private val contentListeners = java.util.concurrent.CopyOnWriteArrayList<() -> Unit>()

    fun addContentListener(listener: () -> Unit) { contentListeners.add(listener) }
    fun removeContentListener(listener: () -> Unit) { contentListeners.remove(listener) }
    private fun notifyContentChanged() {
        // Each listener runs on the SSH read thread (background) but
        // typically calls View.invalidate() or Compose state writes that
        // ultimately post to the main thread. Wrap each invocation
        // individually so one broken listener does not skip the rest
        // (e.g. a detached TerminalView's invalidate racing with a
        // widget's render trigger). The outer read loop is already
        // wrapped in SshSession, but that catch is coarse — isolating
        // per-listener prevents a stale listener from poisoning a fresh
        // one.
        for (l in contentListeners) {
            try {
                l()
            } catch (t: Throwable) {
                AppLogger.w(Category.TERMINAL) {
                    "emu.contentListener threw, dropping: ${t.javaClass.simpleName}: ${t.message}"
                }
            }
        }
    }

    // -- Saved cursor (DECSC / DECRC) -----------------------------------

    private var savedCursorRow: Int = 0
    private var savedCursorCol: Int = 0
    private var savedFg: Int = CellEncoding.DEFAULT_FG
    private var savedBg: Int = CellEncoding.DEFAULT_BG
    private var savedBold: Boolean = false
    private var savedItalic: Boolean = false
    private var savedUnderline: Boolean = false
    private var savedStrikethrough: Boolean = false
    private var savedDim: Boolean = false
    private var savedOriginMode: Boolean = false

    // -- Current text attributes ----------------------------------------

    private var currentFg: Int = CellEncoding.DEFAULT_FG
    private var currentBg: Int = CellEncoding.DEFAULT_BG
    private var currentBold: Boolean = false
    private var currentItalic: Boolean = false
    private var currentUnderline: Boolean = false
    private var currentStrikethrough: Boolean = false
    private var currentDim: Boolean = false
    private var reverseVideo: Boolean = false
    private var hidden: Boolean = false

    // -- Terminal modes --------------------------------------------------

    var applicationCursorKeys: Boolean = false
        private set
    var originMode: Boolean = false
        private set
    var wraparoundMode: Boolean = true
        private set
    var insertMode: Boolean = false
        private set
    var bracketedPasteMode: Boolean = false
        private set

    // -- Scroll region (DECSTBM) ----------------------------------------

    private var scrollTop: Int = 0
    private var scrollBottom: Int = rows - 1

    // -- Alternate screen buffer ----------------------------------------

    private var altBuffer: TerminalBuffer? = null
    private var mainBuffer: TerminalBuffer? = null
    private var usingAltScreen: Boolean = false

    // Saved cursor for the main screen (preserved when switching to alt)
    private var mainSavedCursorRow: Int = 0
    private var mainSavedCursorCol: Int = 0

    // -- Last printed character (for REP / CSI b) -------------------------

    private var lastPrintedCodePoint: Int = ' '.code

    // -- DEC Line Drawing charset ----------------------------------------

    private var useLineDrawingCharset: Boolean = false
    private var savedUseLineDrawingCharset: Boolean = false
    private var charsetDesignatorTarget: Int = 0

    private val decLineDrawingMap = mapOf(
        'j'.code to 0x2518,  // ┘ (lower right corner)
        'k'.code to 0x2510,  // ┐ (upper right corner)
        'l'.code to 0x250C,  // ┌ (upper left corner)
        'm'.code to 0x2514,  // └ (lower left corner)
        'n'.code to 0x253C,  // ┼ (crossing lines)
        'q'.code to 0x2500,  // ─ (horizontal line)
        't'.code to 0x251C,  // ├ (left tee)
        'u'.code to 0x2524,  // ┤ (right tee)
        'v'.code to 0x2534,  // ┴ (bottom tee)
        'w'.code to 0x252C,  // ┬ (top tee)
        'x'.code to 0x2502,  // │ (vertical line)
        'a'.code to 0x2592,  // ▒ (checkerboard)
        'f'.code to 0x00B0,  // ° (degree)
        'g'.code to 0x00B1,  // ± (plus/minus)
        'o'.code to 0x23BA,  // ⎺ (scan line 1)
        's'.code to 0x23BD,  // ⎽ (scan line 9)
        '`'.code to 0x25C6,  // ◆ (diamond)
    )

    // -- Tab stops -------------------------------------------------------

    private val tabStops: java.util.TreeSet<Int> = java.util.TreeSet<Int>().apply {
        for (i in 0 until 320 step 8) add(i)
    }

    // -- Parser state ----------------------------------------------------

    private enum class State {
        NORMAL,
        ESC,
        CSI_PARAM,
        CSI_INTERMEDIATE,
        OSC,
        CHARSET_DESIGNATOR
    }

    private var state: State = State.NORMAL

    /** Accumulated CSI parameter bytes (digits and semicolons). */
    private val csiParams = StringBuilder()
    /** Accumulated CSI intermediate bytes (e.g. '?' or '>'). */
    private val csiIntermediate = StringBuilder()
    /** Accumulated OSC string content. */
    private val oscData = StringBuilder()

    // -- UTF-8 decoder state ---------------------------------------------

    /** Bytes remaining in the current multi-byte character. */
    private var utf8Remaining: Int = 0
    /** Code point being assembled. */
    private var utf8CodePoint: Int = 0

    // ====================================================================
    // Main entry point
    // ====================================================================

    /**
     * Processes raw bytes from the PTY/SSH channel.  This is the sole input
     * method; it handles UTF-8 decoding and all escape sequence parsing.
     */
    fun processInput(data: ByteArray) {
        synchronized(lock) {
            for (b in data) {
                processByte(b)
            }
        }
        notifyContentChanged()
    }

    /** Convenience overload for a subsection of a byte array. */
    fun processInput(data: ByteArray, offset: Int, length: Int) {
        synchronized(lock) {
            for (i in offset until (offset + length).coerceAtMost(data.size)) {
                processByte(data[i])
            }
        }
        notifyContentChanged()
    }

    // ====================================================================
    // Resize
    // ====================================================================

    /**
     * Resizes the terminal to [newRows] x [newCols].
     * Adjusts the buffer, scroll region, and cursor position.
     */
    fun resize(newRows: Int, newCols: Int) {
        if (newRows <= 0 || newCols <= 0) {
            AppLogger.w(Category.TERMINAL) { "emu.resize REJECT newRows=$newRows newCols=$newCols" }
            return
        }
        AppLogger.i(Category.TERMINAL) { "emu.resize ${rows}x${columns} → ${newRows}x${newCols} alt=$usingAltScreen" }
        synchronized(lock) {
            val oldRows = rows
            buffer.resize(newRows, newCols)
            // Resize whichever buffer is not currently active
            if (usingAltScreen) {
                mainBuffer?.resize(newRows, newCols)
            } else {
                altBuffer?.resize(newRows, newCols)
            }
            rows = newRows
            columns = newCols
            scrollTop = 0
            scrollBottom = rows - 1
            // When shrinking, excess top lines are pushed to scrollback.
            // Adjust cursor row to match the shift.
            if (newRows < oldRows) {
                val excess = oldRows - newRows
                cursorRow = (cursorRow - excess).coerceIn(0, newRows - 1)
            } else {
                cursorRow = cursorRow.coerceIn(0, newRows - 1)
            }
            cursorCol = cursorCol.coerceIn(0, columns - 1)
        }
    }

    fun setMaxScrollback(lines: Int) {
        val clamped = lines.coerceAtLeast(0)
        synchronized(lock) {
            if (clamped == maxScrollback) return
            maxScrollback = clamped
            if (usingAltScreen) {
                mainBuffer = mainBuffer?.withMaxScrollback(clamped)
            } else {
                buffer = buffer.withMaxScrollback(clamped)
            }
        }
        notifyContentChanged()
    }

    // ====================================================================
    // Snapshot
    // ====================================================================

    /**
     * Creates an immutable snapshot of the current terminal state.
     * Thread-safe — acquires the emulator lock.
     */
    fun snapshot(): TerminalSnapshot = synchronized(lock) {
        buffer.snapshot(cursorRow, cursorCol, cursorVisible)
    }

    // ====================================================================
    // Byte-level processing
    // ====================================================================

    private fun processByte(b: Byte) {
        val unsigned = b.toInt() and 0xFF

        // --- UTF-8 continuation handling ---
        if (utf8Remaining > 0) {
            if (unsigned and 0xC0 == 0x80) {
                utf8CodePoint = (utf8CodePoint shl 6) or (unsigned and 0x3F)
                utf8Remaining--
                if (utf8Remaining == 0) {
                    handleCodePoint(utf8CodePoint)
                }
                return
            } else {
                // Malformed: reset and reprocess this byte
                utf8Remaining = 0
            }
        }

        // --- State machine dispatch ---
        when (state) {
            State.NORMAL -> processNormal(unsigned)
            State.ESC -> processEsc(unsigned)
            State.CSI_PARAM -> processCsiParam(unsigned)
            State.CSI_INTERMEDIATE -> processCsiIntermediate(unsigned)
            State.OSC -> processOsc(unsigned)
            State.CHARSET_DESIGNATOR -> processCharsetDesignator(unsigned)
        }
    }

    // ====================================================================
    // NORMAL state
    // ====================================================================

    private fun processNormal(code: Int) {
        when {
            // C0 control characters
            code == 0x07 -> handleBell()
            code == 0x08 -> handleBackspace()
            code == 0x09 -> handleTab()
            code == 0x0A || code == 0x0B || code == 0x0C -> handleLineFeed()
            code == 0x0D -> handleCarriageReturn()
            code == 0x1B -> {
                state = State.ESC
            }
            // Ignore NUL, SOH-ACK, SO, SI, DLE-SUB, FS-US, DEL
            code < 0x20 || code == 0x7F -> { /* ignore */ }
            // UTF-8 start bytes
            code and 0xE0 == 0xC0 -> {
                utf8CodePoint = code and 0x1F
                utf8Remaining = 1
            }
            code and 0xF0 == 0xE0 -> {
                utf8CodePoint = code and 0x0F
                utf8Remaining = 2
            }
            code and 0xF8 == 0xF0 -> {
                utf8CodePoint = code and 0x07
                utf8Remaining = 3
            }
            // Plain ASCII printable
            else -> handlePrintable(code.toChar())
        }
    }

    // ====================================================================
    // ESC state — saw ESC, waiting for next byte
    // ====================================================================

    private fun processEsc(code: Int) {
        when (code) {
            '['.code -> {
                // CSI introducer
                csiParams.clear()
                csiIntermediate.clear()
                state = State.CSI_PARAM
            }
            ']'.code -> {
                // OSC introducer
                oscData.clear()
                state = State.OSC
            }
            '7'.code -> {
                // DECSC - Save Cursor
                saveCursor()
                state = State.NORMAL
            }
            '8'.code -> {
                // DECRC - Restore Cursor
                restoreCursor()
                state = State.NORMAL
            }
            'D'.code -> {
                // IND - Index (move cursor down, scroll if at bottom)
                handleIndex()
                state = State.NORMAL
            }
            'E'.code -> {
                // NEL - Next Line
                cursorCol = 0
                handleIndex()
                state = State.NORMAL
            }
            'M'.code -> {
                // RI - Reverse Index (move cursor up, scroll down if at top)
                handleReverseIndex()
                state = State.NORMAL
            }
            'H'.code -> {
                // HTS - Horizontal Tab Set
                tabStops.add(cursorCol)
                state = State.NORMAL
            }
            'c'.code -> {
                // RIS - Full Reset
                fullReset()
                state = State.NORMAL
            }
            '('.code, ')'.code, '*'.code, '+'.code -> {
                // Designate character set — consume next byte in CHARSET_DESIGNATOR state
                charsetDesignatorTarget = code
                state = State.CHARSET_DESIGNATOR
            }
            '='.code -> {
                // DECKPAM - Keypad Application Mode (ignore for now)
                state = State.NORMAL
            }
            '>'.code -> {
                // DECKPNM - Keypad Numeric Mode (ignore for now)
                state = State.NORMAL
            }
            '#'.code -> {
                // DEC screen alignment test or double-height/width — skip next byte
                charsetDesignatorTarget = code
                state = State.CHARSET_DESIGNATOR
            }
            else -> {
                // Unknown ESC sequence — ignore and return to normal
                AppLogger.d(Category.TERMINAL) { "emu.esc UNKNOWN code=0x${code.toString(16)}" }
                state = State.NORMAL
            }
        }
    }

    // ====================================================================
    // Charset designator state — consumes the byte after ESC ( / ) / * / + / #
    // ====================================================================

    private fun processCharsetDesignator(code: Int) {
        // Only track G0 (ESC ( ...) for simplicity
        if (charsetDesignatorTarget == '('.code) {
            useLineDrawingCharset = (code == '0'.code)
        }
        state = State.NORMAL
    }

    // ====================================================================
    // CSI parameter collection — CSI already seen, collecting digits/';'
    // ====================================================================

    private fun processCsiParam(code: Int) {
        when {
            // C0 controls that are allowed inside CSI (executed immediately)
            code == 0x07 -> handleBell()
            code == 0x08 -> handleBackspace()
            code == 0x0A || code == 0x0B || code == 0x0C -> handleLineFeed()
            code == 0x0D -> handleCarriageReturn()
            code == 0x1B -> {
                // ESC interrupts CSI — start over
                state = State.ESC
            }
            // Parameter bytes: 0x30-0x3F (digits, semicolon, colon, <=>?)
            code in 0x30..0x3F -> {
                val ch = code.toChar()
                if (ch == '?' || ch == '>' || ch == '<' || ch == '=') {
                    csiIntermediate.append(ch)
                } else {
                    csiParams.append(ch)
                }
            }
            // Intermediate bytes: 0x20-0x2F (space, !, ", #, $, %, &, ', etc.)
            code in 0x20..0x2F -> {
                csiIntermediate.append(code.toChar())
                state = State.CSI_INTERMEDIATE
            }
            // Final byte: 0x40-0x7E
            code in 0x40..0x7E -> {
                dispatchCsi(code.toChar())
                state = State.NORMAL
            }
            // Anything else: malformed — abort
            else -> state = State.NORMAL
        }
    }

    private fun processCsiIntermediate(code: Int) {
        when {
            code == 0x1B -> state = State.ESC
            code in 0x20..0x2F -> csiIntermediate.append(code.toChar())
            code in 0x40..0x7E -> {
                dispatchCsi(code.toChar())
                state = State.NORMAL
            }
            else -> state = State.NORMAL
        }
    }

    // ====================================================================
    // OSC collection — accumulate until ST (ESC \) or BEL
    // ====================================================================

    private fun processOsc(code: Int) {
        when (code) {
            0x07 -> {
                // BEL terminates OSC
                handleOsc(oscData.toString())
                state = State.NORMAL
            }
            0x1B -> {
                // Could be ST (ESC \).  We peek-ahead by saving state.
                // For simplicity, finish the OSC and go to ESC state.
                // If the next byte is '\', great. Otherwise ESC will
                // be processed normally.  This is how most terminals handle it.
                handleOsc(oscData.toString())
                state = State.ESC
            }
            else -> {
                if (oscData.length < 4096) {
                    oscData.append(code.toChar())
                }
                // else silently discard to avoid unbounded growth
            }
        }
    }

    // ====================================================================
    // OSC dispatch
    // ====================================================================

    private fun handleOsc(data: String) {
        // Format: Ps ; Pt  where Ps is a number
        val semicolonIdx = data.indexOf(';')
        if (semicolonIdx < 0) return
        val ps = data.substring(0, semicolonIdx).toIntOrNull() ?: return
        val pt = data.substring(semicolonIdx + 1)

        when (ps) {
            0, 1, 2 -> {
                // Set window title / icon name
                title = pt
                AppLogger.d(Category.TERMINAL) { "emu.osc.title pt='$pt'" }
                listener?.onTitleChanged(title)
            }
            // Other OSC codes (clipboard, hyperlinks, etc.) are ignored for now.
        }
    }

    // ====================================================================
    // CSI dispatch
    // ====================================================================

    private fun dispatchCsi(finalChar: Char) {
        val params = parseCsiParams(csiParams.toString())
        val prefix = csiIntermediate.toString()

        when (finalChar) {
            // -- Cursor movement --
            'A' -> cursorUp(params.getOrDefault(0, 1))
            'B' -> cursorDown(params.getOrDefault(0, 1))
            'C' -> cursorForward(params.getOrDefault(0, 1))
            'D' -> cursorBackward(params.getOrDefault(0, 1))
            'E' -> {
                // CNL - Cursor Next Line
                cursorDown(params.getOrDefault(0, 1))
                cursorCol = 0
            }
            'F' -> {
                // CPL - Cursor Previous Line
                cursorUp(params.getOrDefault(0, 1))
                cursorCol = 0
            }
            'G' -> {
                // CHA - Cursor Character Absolute
                cursorCol = (params.getOrDefault(0, 1) - 1).coerceIn(0, columns - 1)
            }
            'H', 'f' -> {
                // CUP - Cursor Position
                val row = (params.getOrDefault(0, 1) - 1)
                val col = (params.getOrDefault(1, 1) - 1)
                setCursorPosition(row, col)
            }
            'J' -> handleED(params.getOrDefault(0, 0))
            'K' -> handleEL(params.getOrDefault(0, 0))
            'L' -> {
                // IL - Insert Lines
                val count = params.getOrDefault(0, 1)
                insertLines(count)
            }
            'M' -> {
                // DL - Delete Lines
                val count = params.getOrDefault(0, 1)
                deleteLines(count)
            }
            'P' -> {
                // DCH - Delete Characters
                val count = params.getOrDefault(0, 1)
                deleteChars(count)
            }
            'S' -> {
                // SU - Scroll Up
                if (prefix.isEmpty()) {
                    val count = params.getOrDefault(0, 1)
                    buffer.scrollUpRegion(scrollTop, scrollBottom, count)
                }
            }
            'T' -> {
                // SD - Scroll Down
                if (prefix.isEmpty() && params.size <= 1) {
                    val count = params.getOrDefault(0, 1)
                    buffer.scrollDownRegion(scrollTop, scrollBottom, count)
                }
            }
            'X' -> {
                // ECH - Erase Characters
                val count = params.getOrDefault(0, 1)
                eraseChars(count)
            }
            '@' -> {
                // ICH - Insert Characters
                val count = params.getOrDefault(0, 1)
                insertChars(count)
            }
            'd' -> {
                // VPA - Line Position Absolute
                val row = (params.getOrDefault(0, 1) - 1).coerceIn(0, rows - 1)
                cursorRow = if (originMode) (row + scrollTop).coerceAtMost(scrollBottom) else row
            }
            'm' -> handleSGR(params)
            'n' -> {
                // DSR - Device Status Report
                if (params.getOrDefault(0, 0) == 6) {
                    // CPR - Cursor Position Report
                    val response = "\u001b[${cursorRow + 1};${cursorCol + 1}R"
                    val bytes = response.toByteArray()
                    listener?.onDataOutput(bytes)
                    dataOutputCallback?.invoke(bytes)
                }
            }
            'r' -> {
                // DECSTBM - Set Top and Bottom Margins
                if (prefix.isEmpty()) {
                    val top = (params.getOrDefault(0, 1) - 1).coerceIn(0, rows - 1)
                    val bottom = (params.getOrDefault(1, rows) - 1).coerceIn(0, rows - 1)
                    if (top < bottom) {
                        scrollTop = top
                        scrollBottom = bottom
                    }
                    // Home the cursor
                    setCursorPosition(0, 0)
                }
            }
            'h' -> handleMode(params, prefix, set = true)
            'l' -> handleMode(params, prefix, set = false)
            'g' -> {
                // TBC - Tab Clear
                when (params.getOrDefault(0, 0)) {
                    0 -> tabStops.remove(cursorCol)
                    3 -> tabStops.clear()
                }
            }
            'c' -> {
                // DA - Device Attributes
                if (prefix.isEmpty() || prefix == "?") {
                    // Report as VT220
                    val response = "\u001b[?62c"
                    val bytes = response.toByteArray()
                    listener?.onDataOutput(bytes)
                    dataOutputCallback?.invoke(bytes)
                }
            }
            't' -> {
                // Window manipulation (mostly ignored)
                // Silently ignore
            }
            'b' -> {
                // REP - Repeat preceding printable character
                val count = params.getOrDefault(0, 1)
                for (i in 0 until count) {
                    handlePrintable(lastPrintedCodePoint.toChar())
                }
            }
            else -> {
                // Unknown CSI final byte — record so we can spot mangled-output bug reports
                AppLogger.d(Category.TERMINAL) { "emu.csi UNKNOWN final='$finalChar' params=$params prefix='$prefix'" }
            }
        }
    }

    // ====================================================================
    // Helpers for CSI parameters
    // ====================================================================

    /**
     * Parses a CSI parameter string like "1;2;3" or "" into a list of Ints.
     * Missing / empty parameters default to 0.
     */
    private fun parseCsiParams(raw: String): List<Int> {
        if (raw.isEmpty()) return emptyList()
        return raw.split(';').map { it.toIntOrNull() ?: 0 }
    }

    /** Gets a parameter by index, returning [default] if missing. */
    private fun List<Int>.getOrDefault(index: Int, default: Int): Int {
        val v = getOrNull(index)
        return if (v == null || v == 0) default else v
    }

    // ====================================================================
    // Cursor movement
    // ====================================================================

    private fun cursorUp(count: Int) {
        val top = if (cursorRow in scrollTop..scrollBottom) scrollTop else 0
        cursorRow = (cursorRow - count).coerceAtLeast(top)
    }

    private fun cursorDown(count: Int) {
        val bottom = if (cursorRow in scrollTop..scrollBottom) scrollBottom else rows - 1
        cursorRow = (cursorRow + count).coerceAtMost(bottom)
    }

    private fun cursorForward(count: Int) {
        cursorCol = (cursorCol + count).coerceAtMost(columns - 1)
    }

    private fun cursorBackward(count: Int) {
        cursorCol = (cursorCol - count).coerceAtLeast(0)
    }

    private fun setCursorPosition(row: Int, col: Int) {
        cursorCol = col.coerceIn(0, columns - 1)
        cursorRow = if (originMode) {
            (row + scrollTop).coerceIn(scrollTop, scrollBottom)
        } else {
            row.coerceIn(0, rows - 1)
        }
    }

    private fun saveCursor() {
        savedCursorRow = cursorRow
        savedCursorCol = cursorCol
        savedFg = currentFg
        savedBg = currentBg
        savedBold = currentBold
        savedItalic = currentItalic
        savedUnderline = currentUnderline
        savedStrikethrough = currentStrikethrough
        savedDim = currentDim
        savedOriginMode = originMode
        savedUseLineDrawingCharset = useLineDrawingCharset
    }

    private fun restoreCursor() {
        cursorRow = savedCursorRow.coerceIn(0, rows - 1)
        cursorCol = savedCursorCol.coerceIn(0, columns - 1)
        currentFg = savedFg
        currentBg = savedBg
        currentBold = savedBold
        currentItalic = savedItalic
        currentUnderline = savedUnderline
        currentStrikethrough = savedStrikethrough
        currentDim = savedDim
        originMode = savedOriginMode
        useLineDrawingCharset = savedUseLineDrawingCharset
    }

    // ====================================================================
    // Printable character handling
    // ====================================================================

    private fun handleCodePoint(codePoint: Int) {
        if (codePoint < 0x20) return // control character in multi-byte — ignore
        if (codePoint <= 0xFFFF) {
            handlePrintable(codePoint.toChar())
        } else {
            // Supplementary plane: encode as surrogate pair.
            // For terminal purposes we treat this as a single wide character;
            // we store the high surrogate and fill the next cell with a placeholder.
            val high = ((codePoint - 0x10000) shr 10) + 0xD800
            handlePrintable(high.toChar())
        }
    }

    private fun handlePrintable(ch: Char) {
        // Apply DEC line drawing substitution if active
        val mapped = if (useLineDrawingCharset) {
            decLineDrawingMap[ch.code]?.toChar() ?: ch
        } else {
            ch
        }

        // Determine effective fg/bg (handle reverse video)
        val effectiveFg = if (reverseVideo) currentBg else currentFg
        val effectiveBg = if (reverseVideo) currentFg else currentBg
        val displayChar = if (hidden) ' ' else mapped

        val packed = CellEncoding.encode(
            displayChar.code, effectiveFg,
            currentBold, currentItalic, currentUnderline,
            currentStrikethrough, currentDim, false
        )
        val color = CellEncoding.encodeBg(effectiveBg)

        // Handle wraparound
        if (cursorCol >= columns) {
            if (wraparoundMode) {
                cursorCol = 0
                handleIndex() // move down / scroll
            } else {
                cursorCol = columns - 1
            }
        }

        // Wide chars need 2 columns — if only 1 remains, wrap first
        val wide = isWideChar(displayChar)
        if (wide && cursorCol + 1 >= columns && wraparoundMode) {
            cursorCol = 0
            handleIndex()
        }

        if (insertMode) {
            // Shift characters to the right
            insertChars(1)
        }

        buffer.setCell(cursorRow, cursorCol, packed, color)
        lastPrintedCodePoint = displayChar.code

        // Wide characters occupy two columns: fill the continuation cell
        // and advance cursor by 2 instead of 1.
        if (wide && cursorCol + 1 < columns) {
            val phPacked = CellEncoding.encode(' '.code, CellEncoding.DEFAULT_FG, bold = false, italic = false, underline = false, strikethrough = false, dim = false, widePlaceholder = true)
            val phColor = CellEncoding.encodeBg(effectiveBg)
            buffer.setCell(cursorRow, cursorCol + 1, phPacked, phColor)
            cursorCol += 2
        } else {
            cursorCol++
        }
    }

    // ====================================================================
    // Control character handlers
    // ====================================================================

    private fun handleBell() {
        AppLogger.d(Category.TERMINAL) { "emu.bell" }
        listener?.onBellRing()
    }

    private fun handleBackspace() {
        if (cursorCol > 0) cursorCol--
    }

    private fun handleTab() {
        val nextTab = tabStops.higher(cursorCol)
        cursorCol = if (nextTab != null) {
            nextTab.coerceAtMost(columns - 1)
        } else {
            columns - 1
        }
    }

    private fun handleLineFeed() {
        handleIndex()
    }

    private fun handleCarriageReturn() {
        cursorCol = 0
    }

    /**
     * IND — Index: move cursor down one line.  If the cursor is on the
     * bottom margin of the scroll region, scroll the region up instead.
     */
    private fun handleIndex() {
        if (cursorRow == scrollBottom) {
            buffer.scrollUpRegion(scrollTop, scrollBottom, 1)
        } else if (cursorRow < rows - 1) {
            cursorRow++
        }
    }

    /**
     * RI — Reverse Index: move cursor up one line.  If the cursor is on the
     * top margin of the scroll region, scroll the region down instead.
     */
    private fun handleReverseIndex() {
        if (cursorRow == scrollTop) {
            buffer.scrollDownRegion(scrollTop, scrollBottom, 1)
        } else if (cursorRow > 0) {
            cursorRow--
        }
    }

    // ====================================================================
    // ED — Erase in Display
    // ====================================================================

    private fun handleED(mode: Int) {
        when (mode) {
            0 -> {
                // Erase from cursor to end of display (uses current bg per spec)
                clearLineFrom(cursorRow, cursorCol)
                for (r in cursorRow + 1 until rows) {
                    clearWholeLine(r)
                }
            }
            1 -> {
                // Erase from start of display to cursor (uses current bg per spec)
                for (r in 0 until cursorRow) {
                    clearWholeLine(r)
                }
                clearLineTo(cursorRow, cursorCol)
            }
            2 -> {
                // Erase entire display (uses current bg per spec)
                for (r in 0 until rows) {
                    clearWholeLine(r)
                }
            }
            3 -> {
                // Erase entire display + scrollback
                for (r in 0 until rows) {
                    clearWholeLine(r)
                }
                buffer.clearScrollback()
            }
        }
    }

    // ====================================================================
    // EL — Erase in Line
    // ====================================================================

    private fun handleEL(mode: Int) {
        when (mode) {
            0 -> clearLineFrom(cursorRow, cursorCol)   // cursor to end
            1 -> clearLineTo(cursorRow, cursorCol)       // start to cursor
            2 -> clearWholeLine(cursorRow)               // whole line
        }
    }

    /** Clears cells from [startCol] to end of line using current SGR background. */
    private fun clearLineFrom(row: Int, startCol: Int) {
        val clearColor = CellEncoding.encodeBg(currentBg)
        for (c in startCol until columns) {
            buffer.setCell(row, c, CellEncoding.EMPTY_PACKED, clearColor)
        }
    }

    /** Clears cells from start of line to [endCol] using current SGR background. */
    private fun clearLineTo(row: Int, endCol: Int) {
        val clearColor = CellEncoding.encodeBg(currentBg)
        for (c in 0..endCol.coerceAtMost(columns - 1)) {
            buffer.setCell(row, c, CellEncoding.EMPTY_PACKED, clearColor)
        }
    }

    /** Clears an entire line using current SGR background. */
    private fun clearWholeLine(row: Int) {
        val clearColor = CellEncoding.encodeBg(currentBg)
        for (c in 0 until columns) {
            buffer.setCell(row, c, CellEncoding.EMPTY_PACKED, clearColor)
        }
    }

    // ====================================================================
    // IL / DL — Insert / Delete Lines
    // ====================================================================

    private fun insertLines(count: Int) {
        if (cursorRow < scrollTop || cursorRow > scrollBottom) return
        val effective = count.coerceAtMost(scrollBottom - cursorRow + 1)
        buffer.scrollDownRegion(cursorRow, scrollBottom, effective)
    }

    private fun deleteLines(count: Int) {
        if (cursorRow < scrollTop || cursorRow > scrollBottom) return
        val effective = count.coerceAtMost(scrollBottom - cursorRow + 1)
        buffer.scrollUpRegion(cursorRow, scrollBottom, effective)
    }

    // ====================================================================
    // ICH / DCH / ECH — Insert / Delete / Erase Characters
    // ====================================================================

    private fun insertChars(count: Int) {
        val effective = count.coerceAtMost(columns - cursorCol)
        if (effective <= 0) return
        val clearColor = CellEncoding.encodeBg(currentBg)
        // Shift characters right
        for (c in columns - 1 downTo cursorCol + effective) {
            val p = buffer.getRawPacked(cursorRow, c - effective)
            val cl = buffer.getRawColor(cursorRow, c - effective)
            buffer.setCell(cursorRow, c, p, cl)
        }
        // Fill inserted positions with blanks (current bg)
        for (c in cursorCol until (cursorCol + effective).coerceAtMost(columns)) {
            buffer.setCell(cursorRow, c, CellEncoding.EMPTY_PACKED, clearColor)
        }
    }

    private fun deleteChars(count: Int) {
        val effective = count.coerceAtMost(columns - cursorCol)
        if (effective <= 0) return
        val clearColor = CellEncoding.encodeBg(currentBg)
        // Shift characters left
        for (c in cursorCol until columns - effective) {
            val p = buffer.getRawPacked(cursorRow, c + effective)
            val cl = buffer.getRawColor(cursorRow, c + effective)
            buffer.setCell(cursorRow, c, p, cl)
        }
        // Fill vacated positions with blanks (current bg)
        for (c in columns - effective until columns) {
            buffer.setCell(cursorRow, c, CellEncoding.EMPTY_PACKED, clearColor)
        }
    }

    private fun eraseChars(count: Int) {
        val effective = count.coerceAtMost(columns - cursorCol)
        val clearColor = CellEncoding.encodeBg(currentBg)
        for (c in cursorCol until cursorCol + effective) {
            buffer.setCell(cursorRow, c, CellEncoding.EMPTY_PACKED, clearColor)
        }
    }

    // ====================================================================
    // SGR — Select Graphic Rendition
    // ====================================================================

    private fun handleSGR(params: List<Int>) {
        if (params.isEmpty()) {
            resetAttributes()
            return
        }

        var i = 0
        while (i < params.size) {
            when (params[i]) {
                0 -> resetAttributes()
                1 -> currentBold = true
                2 -> currentDim = true
                3 -> currentItalic = true
                4 -> currentUnderline = true
                5, 6 -> { /* blink — not supported visually, but accept */ }
                7 -> reverseVideo = true
                8 -> hidden = true
                9 -> currentStrikethrough = true
                21 -> currentUnderline = true  // doubly-underlined (treat as underline)
                22 -> { currentBold = false; currentDim = false }
                23 -> currentItalic = false
                24 -> currentUnderline = false
                25 -> { /* blink off */ }
                27 -> reverseVideo = false
                28 -> hidden = false
                29 -> currentStrikethrough = false

                // --- Foreground colors ---
                in 30..37 -> currentFg = TerminalColors.get256Color(params[i] - 30)
                38 -> {
                    i = parseExtendedColor(params, i) { color -> currentFg = color }
                    continue
                }
                39 -> currentFg = CellEncoding.DEFAULT_FG

                // --- Background colors ---
                in 40..47 -> currentBg = TerminalColors.get256Color(params[i] - 40)
                48 -> {
                    i = parseExtendedColor(params, i) { color -> currentBg = color }
                    continue
                }
                49 -> currentBg = CellEncoding.DEFAULT_BG

                // --- Bright foreground colors ---
                in 90..97 -> currentFg = TerminalColors.get256Color(params[i] - 90 + 8)

                // --- Bright background colors ---
                in 100..107 -> currentBg = TerminalColors.get256Color(params[i] - 100 + 8)
            }
            i++
        }
    }

    /**
     * Parses extended color specifications: `38;5;n` (256-color) and
     * `38;2;r;g;b` (true color).  Works for both foreground (38) and
     * background (48).
     *
     * @return the updated index into [params] (past the consumed values).
     */
    private fun parseExtendedColor(params: List<Int>, startIndex: Int, apply: (Int) -> Unit): Int {
        var i = startIndex + 1
        if (i >= params.size) return i

        when (params[i]) {
            5 -> {
                // 256-color: 38;5;n
                i++
                if (i < params.size) {
                    apply(TerminalColors.get256Color(params[i]))
                    i++
                }
            }
            2 -> {
                // True color: 38;2;r;g;b
                i++
                if (i + 2 < params.size) {
                    val r = params[i]
                    val g = params[i + 1]
                    val b = params[i + 2]
                    apply(TerminalColors.getTrueColor(r, g, b))
                    i += 3
                }
            }
            else -> i++
        }
        return i
    }

    private fun resetAttributes() {
        currentFg = CellEncoding.DEFAULT_FG
        currentBg = CellEncoding.DEFAULT_BG
        currentBold = false
        currentDim = false
        currentItalic = false
        currentUnderline = false
        currentStrikethrough = false
        reverseVideo = false
        hidden = false
    }

    // ====================================================================
    // Mode setting — DECSET / DECRST
    // ====================================================================

    private fun handleMode(params: List<Int>, prefix: String, set: Boolean) {
        val isDec = prefix.contains('?')

        for (p in params) {
            if (isDec) {
                handleDecMode(p, set)
            } else {
                handleAnsiMode(p, set)
            }
        }
    }

    private fun handleDecMode(mode: Int, set: Boolean) {
        when (mode) {
            1 -> applicationCursorKeys = set
            6 -> {
                // DECOM — Origin Mode
                originMode = set
                setCursorPosition(0, 0)
            }
            7 -> wraparoundMode = set
            12 -> { /* Blinking cursor — visual, ignore */ }
            25 -> cursorVisible = set
            1000, 1002, 1003, 1006, 1015 -> {
                // Mouse tracking modes — acknowledge but don't act
            }
            1049 -> {
                // Alternate screen buffer
                if (set) {
                    switchToAltScreen()
                } else {
                    switchToMainScreen()
                }
            }
            2004 -> {
                bracketedPasteMode = set
                AppLogger.i(Category.TERMINAL) { "emu.bracketed-paste set=$set" }
            }
        }
    }

    private fun handleAnsiMode(mode: Int, set: Boolean) {
        when (mode) {
            4 -> insertMode = set
            20 -> { /* Auto newline mode — ignored */ }
        }
    }

    // ====================================================================
    // Alternate screen buffer
    // ====================================================================

    private fun switchToAltScreen() {
        if (usingAltScreen) return
        AppLogger.i(Category.TERMINAL) { "emu.altscreen ENTER cursor=($cursorRow,$cursorCol) ${rows}x${columns}" }
        usingAltScreen = true

        // Save cursor for main screen
        mainSavedCursorRow = cursorRow
        mainSavedCursorCol = cursorCol
        saveCursor()

        // Save the current (main) buffer reference
        mainBuffer = buffer

        // Create a fresh alt screen buffer with 0 scrollback. Hoist to a
        // local `val` so there is no race where another thread could see
        // `altBuffer` as null between the assignment and the `buffer = ...`
        // read — the `!!` bang was a latent NPE even though it looks safe.
        val alt = TerminalBuffer(rows, columns, maxScrollback = 0)
        altBuffer = alt
        buffer = alt
        cursorRow = 0
        cursorCol = 0
    }

    private fun switchToMainScreen() {
        if (!usingAltScreen) return
        AppLogger.i(Category.TERMINAL) { "emu.altscreen EXIT restored=($mainSavedCursorRow,$mainSavedCursorCol)" }
        usingAltScreen = false

        // Discard the alt screen buffer
        altBuffer = null

        // Restore the original main buffer reference
        mainBuffer?.let { main ->
            buffer = main
        }
        mainBuffer = null

        // Restore cursor
        restoreCursor()
        cursorRow = mainSavedCursorRow.coerceIn(0, rows - 1)
        cursorCol = mainSavedCursorCol.coerceIn(0, columns - 1)
    }

    // ====================================================================
    // Full reset (RIS)
    // ====================================================================

    private fun fullReset() {
        AppLogger.i(Category.TERMINAL) { "emu.RIS ${rows}x${columns} (full reset)" }
        if (usingAltScreen) {
            // Restore main buffer reference before clearing
            mainBuffer?.let { main -> buffer = main }
            usingAltScreen = false
            mainBuffer = null
            altBuffer = null
        }
        buffer.clearAll()
        cursorRow = 0
        cursorCol = 0
        cursorVisible = true
        resetAttributes()
        applicationCursorKeys = false
        originMode = false
        wraparoundMode = true
        insertMode = false
        bracketedPasteMode = false
        scrollTop = 0
        scrollBottom = rows - 1
        title = ""
        tabStops.clear()
        for (i in 0 until 320 step 8) tabStops.add(i)
        useLineDrawingCharset = false
        state = State.NORMAL
        utf8Remaining = 0
    }

    // ====================================================================
    // Wide character detection
    // ====================================================================

    companion object {
        /**
         * Returns true if [c] is a wide (double-column) character such as
         * CJK ideographs, fullwidth forms, or certain East Asian scripts.
         */
        fun isWideChar(c: Char): Boolean {
            val code = c.code
            return (code in 0x1100..0x115F) ||   // Hangul Jamo
                    (code in 0x2E80..0x303E) ||  // CJK Radicals, Kangxi, Ideographic
                    (code in 0x3040..0x33BF) ||  // Hiragana, Katakana, Bopomofo, CJK compat
                    (code in 0x3400..0x4DBF) ||  // CJK Unified Ext A
                    (code in 0x4E00..0x9FFF) ||  // CJK Unified
                    (code in 0xA000..0xA4CF) ||  // Yi
                    (code in 0xAC00..0xD7AF) ||  // Hangul Syllables
                    (code in 0xF900..0xFAFF) ||  // CJK Compatibility Ideographs
                    (code in 0xFE30..0xFE6F) ||  // CJK Compatibility Forms
                    (code in 0xFF01..0xFF60) ||  // Fullwidth forms
                    (code in 0xFFE0..0xFFE6)     // Fullwidth signs
        }
    }
}
